### ISSUE TITLE
PhysicsRigidBody lots of excess logging

### ISSUE THREAD

**Issue by Spliterash** [stephengold/Libbulletjme#22]
After I updated the library to a new version, I don’t remember which one, the whole console turned into
```
[16:38:48] [Server Physics Thread/INFO]: [com.jme3.bullet.objects.PhysicsRigidBody] Created 1903ece3360.
```
![image](https://user-images.githubusercontent.com/22550546/212474913-028d980b-722f-41e7-9313-0a31957de6ee.png)

Can you please change log level inside `com/jme3/bullet/objects/PhysicsRigidBody.java:611`

**Comment by stephengold** [comment]
This results from an intentional change made between v17.3.0 and v17.4.0, at https://github.com/stephengold/Libbulletjme/commit/7d6222fdedc7ad8659d996d8c2291e2f82ee8f88

Prior to the change, rigid-body creation was logged only at the `FINE` logging level. Starting with v17.4.0, it is logged at the `INFO` level, which seems more appropriate.

Since you don't want this logging, the appropriate workaround would be something like:
```java
    PhysicsRigidBody.logger2.setLevel(Level.WARNING);
```

**Comment by Spliterash** [comment]
Thanks
