### ISSUE TITLE
[Question] Which collision form should I use?

### ISSUE THREAD

**Issue by CrazyWords1** [stephengold/Libbulletjme#31]
### I need some advice.

I use bullet for my minecraft server, models use the original format which is written in .json, models consist of cubes (box).

What form of collision do you recommend? I suppose CompoundCollisionShape[...BoxCollisionShapes], can I be right?

There are usually 10 to 1000 cubes in these models.

P.S ( I will provide a screenshot and .json file of the test model for you )

MODEL File -> [pyramid.json](https://github.com/stephengold/Libbulletjme/files/15342570/pyramid.json)
![изображение](https://github.com/stephengold/Libbulletjme/assets/32343185/c3dcde05-5f3f-4b82-a046-d7856f52c4ef)

**Comment by stephengold** [comment]
The Minecraft worlds I've seen were composed of thousands of equal-sized, axis-aligned, cubes arranged in a grid.

You describe a model composed of 10-to-1000 cubes or boxes. However, "cube" is a special case of "box", not a synonym, so immediately there's some confusion and uncertainty.

The shape depicted consists of 8 boxes (not 10-to-1000, not cubes) of varying sizes (not equal-sized) and varying orientations (not axis-aligned). My confusion intensifies.

Because the discrepancies between my understanding of Minecraft, your words, and your picture, I'm not 100% confident I understand you're asking about.

For the pyramid depicted, a compound of 8 box collision shapes, such as you supposed, seems a good choice. The other collision shape to consider (assuming the pyramid does not move) would be `MeshCollisionShape`. Without testing them both in a realistic setting, I can't predict which shape would perform better.

For worlds composed of thousands of equal-sized, axis-aligned, cubes arranged in a grid, further optimizations are possible.

**Comment by stephengold** [comment]
Does the pyramid entity move, or is it fixed in place?

**Comment by stephengold** [comment]
For the entity depicted, a compound of 8 box collision shapes, such as you supposed, seems the best choice.
