### ISSUE TITLE
How to disable these kinds of error outputs

### ISSUE THREAD

**Issue by KianBrose** [stephengold/Libbulletjme#35]
![image](https://github.com/user-attachments/assets/86fe6522-3055-4966-a12a-58b240d63c8b)

How do I disable / completely remove these errors that seem to be printed out by the library?

**Comment by stephengold** [comment]
The brute-force way to mask this warning is to use the `java.util.logging` package:
```java
import java.util.logging.Level;
// ...
PhysicsSpace.logger.setLevel(Level.SEVERE);
```

However, I don't recommend doing so because the warning indicates a bug in code that invokes the library. Instead of masking the warning, you (or whoever wrote the code) should troubleshoot the bug.

The buggy code is either trying to remove rigid bodies that have already been removed, or else it's trying to remove them from a space to which they were never added.

**Comment by stephengold** [comment]
@KianBrose Has your question been adequately answered?

**Comment by KianBrose** [comment]
Ah yes! Apologies for not closing it
